pipeline {
    agent any

    stages {
        stage('Terraform Init...') {
            steps {
                dir('terraform'){
                    sh 'terraform init'
                }
            }
        }
    }
}